-- Assignment 3: Explain the ACID properties of a transaction in your own words. 
-- Write SQL statements to simulate a transaction that includes locking and demonstrate different isolation levels to show concurrency control.

use wiprodb;

-- 1. Read Uncommitted Isolation Level

SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

START TRANSACTION;

SELECT ENAME, SAL
FROM emp
WHERE MGR = 7839 AND SAL < 2460;

COMMIT;

SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

START TRANSACTION;

UPDATE EMP
SET SAL = 3000
WHERE MGR = 7839 AND SAL < 2460;

COMMIT;

SELECT ENAME, SAL
FROM emp
WHERE MGR = 7839 AND SAL < 2460;

-- 2. Read Committed Isolation Level

SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;

START TRANSACTION;

SELECT ENAME, SAL
FROM emp
WHERE MGR = 7839 AND SAL = 3000;

COMMIT;

SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;

START TRANSACTION;

UPDATE EMP
SET SAL = 2460
WHERE MGR = 7839 AND SAL = 3000;

COMMIT;

SELECT ENAME, SAL
FROM emp
WHERE MGR = 7839 AND SAL < 2460;

-- 3. Repeatable Read Isolation Level

SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;

START TRANSACTION;

SELECT ENAME, SAL
FROM emp
WHERE MGR = 7839 AND SAL = 2460;

COMMIT;

SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;

START TRANSACTION;

UPDATE EMP
SET SAL = 3000
WHERE MGR = 7839 AND SAL = 2460;

COMMIT;

SELECT ENAME, SAL
FROM emp
WHERE MGR = 7839 AND SAL = 3000;

-- 4. Serializable Isolation Level

SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;

START TRANSACTION;

SELECT ENAME, SAL
FROM emp
WHERE MGR = 7839 AND SAL = 3000;

COMMIT;

SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;

START TRANSACTION;

UPDATE EMP
SET SAL = 2460
WHERE MGR = 7839 AND SAL = 3000;

COMMIT;

SELECT ENAME, SAL
FROM emp
WHERE MGR = 7839 AND SAL = 2460;